from tkinter import*
import tkinter as tk
from tkinter.messagebox import *
class Test:
    def fun1(obj):
        root=Tk()
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        root.title("Bus Reservation System")
        bus=PhotoImage(file='.\\Bus_for_Project.png')
        Label(root, image=bus).grid(row=0,column=0,columnspan=8,padx=width//2.5)
        Label(root,text='Online Bus Booking System',bg='lightblue',fg='red',font='Arial 18 bold').grid(row=1,column=0,columnspan=8,padx=width//2.5)
        Label(root,text='Name: Debanjan Singha Roy',fg='black',font='Arial 18 bold').grid(row=2,column=0,columnspan=8,padx=width//2.5,pady=height//10)
        Label(root,text='Enrollment Number = 211B406',fg='black',font='Arial 18 bold').grid(row=3,column=0,columnspan=8,padx=width//2.5,pady=height//20)
        Label(root,text='Mobile : 9475240460',fg='black',font='Arial 18 bold').grid(row=4,column=0,columnspan=8,padx=width//2.5,pady=height//20)
        Label(root,text='Submitted To : Dr Mahesh Kumar',bg='lightblue',fg='red',font='Arial 18 bold').grid(row=5,column=0,columnspan=8,padx=width//2.5)
        def function(change=0):
          root.destroy()
          obj.fun2()
        root.bind('<KeyPress>' ,function)
        root.mainloop()
    def fun2(obj):
        root=Tk()
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        root.title("Bus Reservation System")
        bus=PhotoImage(file='.\\Bus_for_Project.png')
        Label(root, image=bus).grid(row=0,column=0,columnspan=5,padx=width//2.5)
        Label(root,text='Online Bus Booking System',bg='lightblue',fg='red',font='Arial 18 bold').grid(row=1,column=0,columnspan=5,padx=width//2.5)
        def Home():
          root.destroy
          obj.fun2()
        def Seat_Booking(change=0):
          root.destroy
          obj.fun3()
        def Add_Bus_Details(change=0):
          root.destroy
          obj.fun4()
        def Check_Booked_Details(change=0):
          root.destroy
          obj.fun5()
        Button(root,text='Seat Booking',height=2,width=15,bg='green',font='Arial 18 bold',command=Seat_Booking).grid(row=4,column=1,pady=height//10)
        Button(root,text='Check Booked Details',height=2,width=20,bg='green',font='Arial 18 bold',command=Check_Booked_Details).grid(row=4,column=2,pady=height//10)
        Button(root,text='Add Bus Details',height=2,width=15,bg='green',font='Arial 18 bold',command=Add_Bus_Details).grid(row=4,column=3,pady=height//10)
        Label(root,text='ADMIN ONLY',fg='red',font='Arial 10 bold').grid(row=5,column=3,pady=height//25)
        root.mainloop()
    def fun3(obj):
        root=Tk()
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        root.title("Bus Reservation System")
        Label(root,text="  ").grid(row=0,column=0,padx=150)
        label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
        bus=PhotoImage(file='.\\Bus_for_Project.png')
        Label(root, image=bus).grid(row=0,column=1,columnspan=6)
        Label1.grid(row=1,column=1,pady=30,columnspan=6)
        Label(root,text="Enter Journey Details",font=("Aerial 15 bold"),fg= "Green",bg="light Green").grid(row=3,column=1,columnspan=6,pady=10)
        Label(root,text="TO",font=("Aerial 15 bold")).grid(row=5,column=1)
        v=Entry(root,width=20).grid(row=5,column=2)
        Label(root,text="FROM",font=("Aerial 15 bold")).grid(row=5,column=3)
        Entry(root,width=20,).grid(row=5,column=4)
        Label(root,text="Journey Date",font=("Aerial 15 bold")).grid(row=5,column=5)
        Entry(root,width=20).grid(row=5,column=6)
        Button(root,text="Show bus",font=(" Aerial 15 bold"),bg="green").grid(row=5,column=7)
        def show_bus():
          Label(root,text="select bus ",fg="green",font=("Aerial 12 bold")).grid(row=6,column=1)
          Label(root,text="Operator",fg="green",font=("Aerial 12 bold")).grid(row=6,column=2)
          Label(root,text="Bus Type",fg="green",font=("Aerial 12 bold")).grid(row=6,column=3,padx=50)
          Label(root,text="Availability",fg="green",font=("Aerial 12 bold")).grid(row=6,column=4)
          Label(root,text="Fare",fg="green",font=("Aerial 12 bold")).grid(row=6,column=5)
        def on_click():
          messagebox.showerror('Error', 'Error: Please complete the entry!')
        pic1=PhotoImage(file='.\\home.png')
        Button(root,image=pic1,command=Home).grid(row=5,column=8,padx=10)
          
        def passeng():
          Label(root,text="Fill Passenger Details to book ticket",font=("Aerial 15 bold"),fg="red",bg="sky blue").grid(row=10,column=2,columnspan=8) 
          Button(root,text="Proceed To Book",font=("Aerial 12 bold"),bg="green",command=passeng).grid(row=8,column=8,pady=20)
        root.mainloop()
    def fun5(obj):
        root=Tk()
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        Label(root,text="  ").grid(row=0,column=0,padx=200)
        label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
        pic=PhotoImage(file='.\\Bus_for_Project.png')
        Label(root,image=pic).grid(row=0,column=1,columnspan=6)
        label1.grid(row=1,column=1,pady=15,columnspan=6)
        Label(root,text="Check your booking",font=("Aerial 20 bold"),fg="green",bg="light green").grid(row=2,column=2,pady=20)
        Label(root,text="Enter your Mobile no.",font=("Aerial 15 bold")).grid(row=4,column=1)
        Entry(root).grid(row=4,column=2)
        Button(root,text="Check Your Booking",font=("Aerial 12 bold")).grid(row=4,column=3)
        root.mainloop()
    def fun4(obj):
        root=Tk()
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        Label(root,text="  ").grid(row=0,column=0,padx=200)
        label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
        pic=PhotoImage(file='.\\Bus_for_Project.png')
        Label(root,image=pic).grid(row=0,column=1,columnspan=4)
        label1.grid(row=1,column=1,pady=15,columnspan=4)
        Label(root,text="Add New Details To Database",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=4)
        def New_Bus():
            root.destroy
            obj.fun7()
        def New_Operator():
            root.destroy
            obj.fun8()
        def New_Route():
            root.destroy
            obj.fun9()
        def New_Run():
            root.destroy
            obj.fun10()
        Button(root,text="New Operator",font=("Aerial 15 bold"),bg="green").grid(row=3,column=1,padx=30)
        Button(root,text="New Bus",font=("Aerial 15 bold"),bg="orange",command=New_Bus).grid(row=3,column=2)
        Button(root,text="New Route",font=("Aerial 15 bold"),bg="sky blue").grid(row=3,column=3,padx=30)
        Button(root,text="New Run",font=("Aerial 15 bold"),bg="purple").grid(row=3,column=4)
        root.mainloop()
    def fun7(obj):
       root=Tk()
       width= root.winfo_screenwidth()
       height= root.winfo_screenheight()
       root.geometry("%dx%d" % (width, height))
       menu= StringVar()
       menu.set("Select Any Language")
       Label(root,text="  ").grid(row=0,column=0,padx=100)
       label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
       pic=PhotoImage(file='.\\Bus_for_Project.png')
       Label(root,image=pic).grid(row=0,column=1,columnspan=12)
       label1.grid(row=1,column=1,pady=15,columnspan=12)
       Label(root,text="ADD BUS DETAILS",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=12)
       Label(root,text="Bus Type",font=("Aerial 15")).grid(row=4,column=1,padx=5)
       Entry(root,width=5).grid(row=4,column=2)
       Label(root,text="Bus id",font=("Aerial 15")).grid(row=4,column=3)
       OptionMenu(root,menu,"AC 2X2","AC 3X2","Non AC 2X2","Non AC 3X2","AC-Sleeper2x1","Non-AC Sleeper 2x1").grid(row=4,column=4)
       Label(root,text="Capacity",font=("Aerial 15")).grid(row=4,column=5)
       Entry(root).grid(row=4,column=6)
       Label(root,text="Fare Rs",font=("Aerial 15")).grid(row=4,column=7)
       Entry(root).grid(row=4,column=8)
       Label(root,text="Operator Id",font=("Aerial 15")).grid(row=4,column=9)
       Entry(root,width=10).grid(row=4,column=10)
       Label(root,text="Route id",font=("Aerial 15")).grid(row=4,column=11)
       Entry(root,width=5).grid(row=4,column=12)
       Button(root,text="Add Bus",bg="green",font=("Aerial 12")).grid(row=10,column=6,pady=70)
       Button(root,text="Edit Bus",bg="green",font=("Aerial 12")).grid(row=10,column=7,padx=5,pady=70)
       pic1=PhotoImage(file='.\\home.png')
       Button(root,image=pic1,command=Home).grid(row=10,column=8,padx=10)
       root.mainloop()

    def fun8(obj):
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        Label(root,text="  ").grid(row=0,column=0,padx=100)
        label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
        pic=PhotoImage(file='.\\Bus_for_Project.png')
        Label(root,image=pic).grid(row=0,column=1,columnspan=12)
        label1.grid(row=1,column=1,pady=15,columnspan=12)
        Label(root,text="ADD BUS OPERATOR DETAIL",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=12)
        Label(root,text="Operator Id",font=("Aerial 15")).grid(row=4,column=1)
        Entry(root,width=5).grid(row=4,column=2)
        Label(root,text="Name",font=("Aerial 15")).grid(row=4,column=3)
        Entry(root,width=7).grid(row=4,column=4)
        Label(root,text="Address",font=("Aerial 15")).grid(row=4,column=5)
        Entry(root).grid(row=4,column=6)
        Label(root,text="Phone",font=("Aerial 15")).grid(row=4,column=7)
        Entry(root).grid(row=4,column=8)
        Label(root,text="Email",font=("Aerial 15")).grid(row=4,column=9)
        Entry(root).grid(row=4,column=10)
        Button(root,text="Add",bg="green",font=("Aerial 12")).grid(row=4,column=11)
        Button(root,text="Edit",bg="green",font=("Aerial 12")).grid(row=4,column=12,padx=5)
        root.mainloop()
    def fun9(obj):
        root=Tk()
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        Label(root,text="  ").grid(row=0,column=0,padx=150)
        label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
        pic=PhotoImage(file='.\\Bus_for_Project.png')
        Label(root,image=pic).grid(row=0,column=1,columnspan=12)
        label1.grid(row=1,column=1,pady=15,columnspan=12)
        Label(root,text="Add Bus Route Detail",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=12)
        Label(root,text="Route id",font=("Aerial 15")).grid(row=4,column=1)
        Entry(root,width=5).grid(row=4,column=2)
        Label(root,text="Station Name",font=("Aerial 15")).grid(row=4,column=3)
        Entry(root,width=15).grid(row=4,column=4)
        Label(root,text="Station Id",font=("Aerial 15")).grid(row=4,column=5)
        Entry(root).grid(row=4,column=6)
        Button(root,text="Add Route",bg="green",font=("Aerial 13")).grid(row=4,column=11)
        Button(root,text="Delete Route",bg="green",font=("Aerial 13")).grid(row=4,column=12,padx=5)
        pic1=PhotoImage(file='.\\home.png')
        Button(root,image=pic1,command=Home).grid(row=10,column=8,padx=10,pady=50)
        root.mainloop()
    def fun10(obj):
        root=Tk()
        width= root.winfo_screenwidth()
        height= root.winfo_screenheight()
        root.geometry("%dx%d" % (width, height))
        Label(root,text="  ").grid(row=0,column=0,padx=150)
        label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
        pic=PhotoImage(file='C:\\Users\\DEBANJAN SINGHA ROY\\OneDrive\\Desktop\\Bus Reservation System\\Bus_for_Project.png')
        Label(root,image=pic).grid(row=0,column=1,columnspan=10)
        label1.grid(row=1,column=1,pady=15,columnspan=10)
        Label(root,text="Add Bus Running Detail",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=10)
        Label(root,text="Bus id",font=("Aerial 15")).grid(row=4,column=1)
        Entry(root,width=5).grid(row=4,column=2)
        Label(root,text="Runing Date",font=("Aerial 15")).grid(row=4,column=3)
        Entry(root,width=15).grid(row=4,column=4)
        Label(root,text="Seat Available",font=("Aerial 15")).grid(row=4,column=5)
        Entry(root).grid(row=4,column=6)
        Button(root,text="Add Run",bg="green",font=("Aerial 13")).grid(row=4,column=8,padx=6)
        Button(root,text="Delete Run",bg="green",font=("Aerial 13")).grid(row=4,column=12,padx=5)
        pic1=PhotoImage(file='C:\\Users\\DEBANJAN SINGHA ROY\\OneDrive\\Desktop\\Bus Reservation System\\home.png')
        Button(root,image=pic1).grid(row=5,column=8,padx=10,pady=50)
        root.mainloop()
t=Test()
t.fun1()

